// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWkr0dpsLt0vThxDNpORWsXAX4Bjx0tA',
    appId: '1:777215089045:web:5938607781f91dbb5d3e9c',
    messagingSenderId: '777215089045',
    projectId: 'rhdatabase-93305',
    authDomain: 'rhdatabase-93305.firebaseapp.com',
    databaseURL: 'https://rhdatabase-93305-default-rtdb.firebaseio.com',
    storageBucket: 'rhdatabase-93305.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAbS8N-oDlSn-b5fDfJpjOHudTe-ZOig',
    appId: '1:777215089045:android:d8b3c3dd31cb195e5d3e9c',
    messagingSenderId: '777215089045',
    projectId: 'rhdatabase-93305',
    databaseURL: 'https://rhdatabase-93305-default-rtdb.firebaseio.com',
    storageBucket: 'rhdatabase-93305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaGyJMxt6JsFhkknOt5YBV7HAUCyCjp14',
    appId: '1:777215089045:ios:83fe8e972139fea05d3e9c',
    messagingSenderId: '777215089045',
    projectId: 'rhdatabase-93305',
    databaseURL: 'https://rhdatabase-93305-default-rtdb.firebaseio.com',
    storageBucket: 'rhdatabase-93305.appspot.com',
    iosBundleId: 'com.example.rpProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaGyJMxt6JsFhkknOt5YBV7HAUCyCjp14',
    appId: '1:777215089045:ios:32a0a5a36842e1ab5d3e9c',
    messagingSenderId: '777215089045',
    projectId: 'rhdatabase-93305',
    databaseURL: 'https://rhdatabase-93305-default-rtdb.firebaseio.com',
    storageBucket: 'rhdatabase-93305.appspot.com',
    iosBundleId: 'com.example.rpProjeto.RunnerTests',
  );
}
